### ISSUE TITLE
importing Js.Date from bucklescript

### ISSUE THREAD

**Issue by idkjs** [cristianoc/genType#377]
I have this repo in which i am exporting a function to typescript.

The generated `.gen.tsx` file as the following error which I can't resolve.

```sh
// Cannot find module './Js.gen'.ts(2307)
import {Date_t as Js_Date_t} from './Js.gen';
```

The line is found in the reproduction, here: https://github.com/idkjs/slots-challenge/blob/8c611525cd2ff1d68683461504c57caad1afd897/src/Get.gen.tsx#L16

There is no `./Js.gen` files so not sure what this is trying to refer to as noted by the `ts` error:
```sh
✖ Failed to compile
(typescript) Error: /Users/prisc_000/working/GitHub/slots-challenge/src/Get.gen.tsx(16,35): semantic error TS2307: Cannot find module './Js.gen'.
Error: /Users/prisc_000/working/GitHub/slots-challenge/src/Get.gen.tsx(16,35): semantic error TS2307: Cannot find module './Js.gen'.
    at error (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
    at /Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24958:23
    at arrayEach (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)
    at Object.transform (/Users/prisc_000/working/GitHub/slots-challenge/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27374:17)
```

Thanks for any guidance.

**Comment by idkjs** [comment]
Resoloved by add `export interface Date_t extends Date {}` shim to project here:https://github.com/idkjs/slots-challenge/blob/558fc162cac8899f726979104a9191918f670afb/src/Js.shim.ts#L1

**Comment by cristianoc** [comment]
Re-opening as a reminder to add date shims to example projects, and perhaps add builtin support.
